# Generated by Django 3.0.7 on 2022-05-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='exams',
            options={'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='posible_answers',
            options={'verbose_name_plural': 'Posible Answers'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelOptions(
            name='user_answers',
            options={'verbose_name_plural': 'User Answers'},
        ),
        migrations.AlterModelOptions(
            name='user_courses',
            options={'verbose_name_plural': 'User Courses'},
        ),
        migrations.RemoveField(
            model_name='posible_answers',
            name='type',
        ),
        migrations.AddField(
            model_name='posible_answers',
            name='is_correct',
            field=models.BooleanField(null=True, verbose_name='es correcta'),
        ),
    ]
