# Generated by Django 3.0.7 on 2022-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220511_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posible_answers',
            name='is_correct',
            field=models.BooleanField(verbose_name='es correcta'),
        ),
    ]
