# Generated by Django 3.0.7 on 2022-05-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220511_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posible_answers',
            name='created_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='posible_answers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
