# Generated by Django 3.0.7 on 2022-05-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220511_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_courses',
            name='progress_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
