# Generated by Django 3.0.7 on 2022-05-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220516_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
