# Generated by Django 3.0.7 on 2022-05-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_courses_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exams',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='course_id',
            new_name='course',
        ),
    ]
