# Generated by Django 3.0.7 on 2022-05-18 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220518_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_answers',
            old_name='question_id',
            new_name='question',
        ),
    ]
