# Generated by Django 3.0.7 on 2022-05-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220518_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Courses'),
        ),
    ]
