# Generated by Django 3.0.7 on 2022-05-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220518_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answers',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='user_answers',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='user_answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='user_answers',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_courses',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='user_courses',
            old_name='user_id',
            new_name='user',
        ),
    ]
