# Generated by Django 3.0.7 on 2022-05-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220518_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='time',
            field=models.IntegerField(),
        ),
    ]
