# Generated by Django 3.0.7 on 2022-05-19 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220519_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Exams'),
        ),
    ]
