# Generated by Django 3.0.7 on 2022-05-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_all_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_user_answers',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Courses'),
        ),
    ]
