# Generated by Django 3.0.7 on 2022-05-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_all_user_answers_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_user_answers',
            name='answer',
        ),
    ]
