# Generated by Django 3.0.7 on 2022-05-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_all_user_answers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_user_answers',
            name='user',
            field=models.IntegerField(),
        ),
    ]
