# Generated by Django 3.0.7 on 2022-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220519_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_user_answers',
            name='course',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_user_answers',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
